name: master and pr builds for ansible roles

on:
  workflow_call:
    secrets:
      gh_token:
        required: true

jobs:
  build:
    name: Ansible lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Lint Ansible Playbook
        uses: ansible/ansible-lint-action@main
      - name: Install Dependencies
        run: pip install ansible
      - name: Create ansible.cfg with correct roles_path
        run: printf '[defaults]\nroles_path=../:./' >ansible.cfg
      # - name: Run ansible syntax-check
      #   run: ansible-playbook tests/test.yml -i tests/inventory --syntax-check
