name: Funding Publisher
on:
  push:
    branches: ['develop', 'main']
    paths:
      - 'funding/**'
  workflow_dispatch:

jobs:
  publish-workflow-template:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target_repo: [
          'cheats',
          'free-dev-resources',
          'atlantis-docker-image',
          'ansible-role-cloudflared',
          'ansible-role-crowdsec',
          'ansible-role-diskmounter',
          'ansible-role-systemd_notifiers',
          'ansible-role-ttrss',
          'ansible-role-backup',
          'ansible-role-git'
        ]
    steps:
      - name: Checkout source repo
        uses: actions/checkout@v3
        with:
          path: main
      - name: Checkout target repo
        uses: actions/checkout@v3
        with:
          repository: ${{ github.repository_owner }}/${{ matrix.target_repo }}
          path: ${{ matrix.target_repo }}
          token: ${{ secrets.GH_TOKEN}}
          ref: main
      - name: Update workflows
        shell: bash
        run: |
          mkdir -p .github/workflows/
          cp ../main/funding/* .github/
        working-directory: ./${{ matrix.target_repo }}
      - name: Publish workflows
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "ci: update funding info"
          commit_user_email: papanito@wyssmann.com
          commit_user_name: GitHub Actions
          repository: ./${{ matrix.target_repo }}
        continue-on-error: false