name: Workflow Publisher (test)
on:
  push:
    branches: [ 'develop',  'main' ]
    paths:
    - 'ansible-roles/**'
  workflow_dispatch:

jobs:
  publish-workflow-template:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target_repo: [
          'ansible-role-test-repo'
        ]
    steps:
      - name: Checkout Workflows
        uses: actions/checkout@v2
        with:
          path: main
      - name: Checkout target repo
        uses: actions/checkout@v2
        with:
          repository: ${{ github.repository_owner }}/${{ matrix.target_repo }}
          path: ${{ matrix.target_repo }}
          token: ${{ secrets.GH_TOKEN}}
          ref: main
      - name: Update workflows
        shell: bash
        run: |
          mkdir -p .github/workflows/
          cp ../main/ansible-roles/* .github/workflows/
        working-directory: ./${{ matrix.target_repo }}
      - name: Publish workflows
        shell: bash
        run: |
          git config --local user.email "papanito@wyssmann.com"
          git config --local user.name "GitHub Actions"
          git add .
          git commit -m "ci: updated workflows"
          git push
        working-directory: ./${{ matrix.target_repo }}